apiVersion: v1
kind: Service
metadata:
  name: brewmind-active
spec:
  selector:
    app: brewmind-ai
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30090
  type: NodePort

