apiVersion: v1
kind: Service
metadata:
  name: brewmind-ai-service
spec:
  selector:
    app: brewmind-ai
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort
